### ISSUE TITLE
.prefire.yml ignored by PrefirePlaybook plugin 

### ISSUE THREAD

**Issue by szymon-heetch** [BarredEwe/Prefire#52] opened 2024-05-07 13:40 UTC
## Context 🕵️‍♀️
Just updated from 1.5.0 to 2.3.0. I use playbook and tests plugins for my target. 
Configuration file uses `- preview_default_enabled: false` to manually choose previews for snapshots and playbook view.

`.prefire.yml` content:
```yaml
test_configuration:
  - preview_default_enabled: false
  - target: [Redacted]
  - simulator_device: "iPhone15,2"
  - required_os: 16
  - snapshot_devices:
    - iPhone 14 Pro

prefire_configuration:
  - preview_default_enabled: false

```

## What 🌱
Running Prefire Tests plugin:
![PrefireTests](https://github.com/BarredEwe/Prefire/assets/78354061/8ebc7265-cd3c-47e1-9264-f9d9c083f17c)

Running Prefire Playbook plugin:
![PrefirePlaybook](https://github.com/BarredEwe/Prefire/assets/78354061/e35c33d9-2a36-4cc3-9e2b-52fe83a85efc)

**Comment by BarredEwe** [comment] 2024-05-07 19:56
@szymon-heetch Thanks for starting the issue!
I posted a new version with a fix for this: https://github.com/BarredEwe/Prefire/releases/tag/2.3.1

**Comment by szymon-heetch** [comment] 2024-05-08 07:25
Thanks for fast reply @BarredEwe! 
I see some inconsistencies tho.
I still use config above. Here what I observed:

### PrefirePlaybookPlugin
#### `#Preview` macro
- `preview_default_enabled: false` setting is still ignored - all my previews are automatically generated. When I add `.prefireIgnored()` explicitly, then it's skipped from generation (correct behavior), but I think it should be skipped automatically and `.prefireEnabled()` should mark previews for generation only. 
#### `PrefireProvider` protocol conformance
-  all previews marked with above protocol are correctly generated. I believe setting `preview_default_enabled: false` only applies to macros (correct me if I'm wrong).

### PrefireTestPlugin
Nothing is generated in both cases (`#Preview` and `PrefireProvider`)

Running Test plugin with config:
```
test_configuration:
  ....
  - preview_default_enabled: true

prefire_configuration:
  - preview_default_enabled: false
```
gets last `preview_default_enabled: false` settings (`test_configuration` and `prefire_configuration` sections are ignored).

### My test scenario
- Single framework
- Use configuration `.yml` above
- **Exclusively** use `PrefirePlaybookPlugin` or `PrefireTestPlugin` (never both at the same time)

**Comment by BarredEwe** [comment] 2024-05-08 08:47
There is a problem in the documentation Readme.md . That's not what the playbook configuration is called right now.

```yaml
test_configuration:
  - preview_default_enabled: true

playbook_configuration:
  - preview_default_enabled: false
```

**Comment by szymon-heetch** [comment] 2024-05-08 10:03
>You need to use playbook_configuration instead of prefire_configuration
Ok, that indeed solves first issue 😅

Still no snapshots tests 🤔

**Comment by BarredEwe** [comment] 2024-05-08 11:20
> > You need to use playbook_configuration instead of prefire_configuration
> 
> Ok, that indeed solves first issue 😅
> 
> Still no snapshots tests 🤔

Which version of Prefire are you using?

**Comment by szymon-heetch** [comment] 2024-05-08 11:48
Updated from 1.5.0 to 2.4.0.

**Comment by BarredEwe** [comment] 2024-05-08 13:54
Can you check if the Prefire has identified it correctly:
```
Prefire configuration
→ Target used for tests: -
→ Tests target: -
```

**Comment by szymon-heetch** [comment] 2024-05-08 14:24
![image](https://github.com/BarredEwe/Prefire/assets/78354061/fba4755e-f902-4da2-9c61-751d7f6e4276)
I followed the path to generated sources and `PreviewModels.generated.swift` doesn't have any models added.

It's reproducible when I use only `PrefireTestPlugin` in my test target - no Playbook plugin used.

**Comment by BarredEwe** [comment] 2024-05-08 18:26
> ![image](https://private-user-images.githubusercontent.com/78354061/328922871-fba4755e-f902-4da2-9c61-751d7f6e4276.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxOTI5NjIsIm5iZiI6MTcxNTE5MjY2MiwicGF0aCI6Ii83ODM1NDA2MS8zMjg5MjI4NzEtZmJhNDc1NWUtZjkwMi00ZGEyLTljNjEtNzUxZDdmNmU0Mjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE4MjQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZjEwNjg0MzI5M2E2NTkxN2I3NTM5Zjk0YmE0NGY5ZjUxZDFkMjkxNmVkNGI3YmZhMmJiMzkzMjc3NTFiZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ax5O_AQmWwfLqx6pHfB1loOMBWlF-lkVk0u4y6-qr9Y) I followed the path to generated sources and `PreviewModels.generated.swift` doesn't have any models added.
> 
> It's reproducible when I use only `PrefireTestPlugin` in my test target - no Playbook plugin used.

I tried it in different ways, connected only PrefireTestPlugin and so on. I can't reproduce the problem. If you can describe a simple case of how to reproduce this problem, it will help me a lot 😊

**Comment by szymon-heetch** [comment] 2024-05-08 20:14
I created sample [project](https://github.com/szymon-heetch/prefire-issue) which mimics my setup - the lead could be that tests are separated to separate Framework 🤔

**Comment by szymon-heetch** [comment] 2024-05-09 09:14
I dug a  bit by myself and found out that list of files passed to sourcery is from app target instead framework.
```yaml
sources:
  - /Users/.../prefire-issue/PrefireIssue/PrefireIssue/ContentView.swift
  - /Users/.../prefire-issue/PrefireIssue/PrefireIssue/PrefireIssueApp.swift
```

**Comment by BarredEwe** [comment] 2024-05-12 09:33
> EDIT 2: Or be super explicit and support Frameworks with naming pattern - `<FrameworkName>` & `<FrameworkName>Tests` :
> 
> ```
> $0.displayName + "Tests" == target.displayName
> ```

That's a great idea. I think this approach will allow not to access the configuration via yml so often. I'll try to implement it now!

**Comment by BarredEwe** [comment] 2024-05-17 08:16
Fixed in release: https://github.com/BarredEwe/Prefire/releases/tag/2.5.0

**Closed by BarredEwe** 2024-05-17 08:16 UTC
Labels: bug
